services:
  db:
    container_name: mongo-db
    image: mongo:5.0.16
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    restart: always
